# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

minecraft_version=26.2

# Fabric Properties
fabric_loader_version=0.19.3
fabric_api_version=0.157.0+26.2

# Mod Properties
mod_version = 1.1.11
maven_group = com.gmail.sneakdevs
archives_base_name = diamondsauctionhouse

# Dependencies
cloth_config_version=26.2.155
sgui_version=2.1.0+26.2
diamond_economy_version=1.5.11
diamond_economy_hash=d8110223f073911468875390637d05258e4d186e